version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.19.2/"
replacements:
  name: "NotEnoughAnimations"
  id: "notenoughanimations"
  version: "1.6.4"
  relocationpackage: "dev.tr7zw.notenoughanimations"
  modrinthid: MPCX6s5C
  curseforgeid: 433760
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  NEAFabric:
    template: "Fabric"
  NEAForge:
    template: "Forge"